[project]
name = "miseenprodfastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "joblib>=1.5.2",
    "mlflow>=3.4.0",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.37.0",
]
